webapp:
  replicaCount: 1

  image:
    repository: dinesh1705/webapp
    pullPolicy: IfNotPresent
    tag: "0.0.4"

  imagePullSecrets: []

  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000

  ingress:
    enabled: false
    className: ""
    annotations: 
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: webapp.localhost
        paths:
          - path: /
            pathType: Prefix
    tls: []

  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  # livenessProbe:
  #   httpGet:
  #     path: /health
  #     port: http
  # readinessProbe:
  #   httpGet:
  #     path: /health
  #     port: http

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

  volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

  nodeSelector: {}

  tolerations: []

  affinity: {}
